Implementation_of_user_api
AnkushM123/Zoho_leave_tracker pull request #5
Opened 2024-01-16 11:05 UTC by AnkushM123

I have implemented user api with validation and swagger implementation

2024-01-17 06:41 UTC, RavirajSuryavanshi requested changes

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +    const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
Please explain the regex logic here in comments.

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +  if (!req.body.name.trim() || !req.body.address.trim() || !req.body.mobile.trim() || !req.body.gender.trim() || req.body.roles.length == 0 || !req.body.email.trim() || !req.body.password.trim() || r
What will happen if the body.name/address/mobile etc filled is not passed in the request?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +    return res.status(400).send("name,address,age,mobile,gender,role,email and password are required fields");
The validation/error message should be specific and not generic. Please ensure we provide information which is relevant to the user and not confusing

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +  if (req.body.age < 0 || req.body.age > 60) {
In the above if control we are checking age < 1 and here we are checking for age < 0. What is the reason behind diff checks here?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +  const add = JSON.parse(req.body.address)
The name of the variables should be meaningful. "Add" can have multiple meanings

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +    roles: req.body.roles.split(','),
We are accepting the body.roles as an array then why are we spliting it?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +    return res.status(401).json({ error: 'Unauthorized: Token missing' });
Any sort of response should come from resourcing files and should not be a hard coded string

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +    if (data.length==0) {
What if the data is null here?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/login.js
> +      const token = jwt.sign(user, process.env.secretKey, { expiresIn: '1h' });
expiresIn should not be hard coded

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/user.js
> +  let isValidObjectId = (id) => {
What is the validation that we are trying apply here?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/user.js
> +      return res.status(404).json("No data found");
Why are we returning 404?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/user.js
> +    const _email = await userService.getUserByEmail(req.body.email);
why we are using const here?

2024-01-17 06:41 UTC, RavirajSuryavanshi commented on apis/user.js
> +  const validatePassword = (password) => {
this code is repeated many time

2024-01-18 13:27 UTC, ix-pankajk requested changes

2024-01-18 13:27 UTC, ix-pankajk commented on core/services/user-service.js
> +}
apply filter on id

2024-01-19 11:15 UTC, ix-pankajk approved these changes

2024-01-19 11:17 UTC, merged